/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CategoriasForm: typeof import('./src/components/CategoriasForm.vue')['default']
    CategoriasList: typeof import('./src/components/CategoriasList.vue')['default']
    ComprasResumoList: typeof import('./src/components/ComprasResumoList.vue')['default']
    DespesasModeloForm: typeof import('./src/components/DespesasModeloForm.vue')['default']
    DespesasModeloList: typeof import('./src/components/DespesasModeloList.vue')['default']
    LancamentosForm: typeof import('./src/components/LancamentosForm.vue')['default']
    LancamentosList: typeof import('./src/components/LancamentosList.vue')['default']
    ParcelasDetailDialog: typeof import('./src/components/ParcelasDetailDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubcategoriasForm: typeof import('./src/components/SubcategoriasForm.vue')['default']
    SubcategoriasList: typeof import('./src/components/SubcategoriasList.vue')['default']
  }
}
