# Generated by Django 5.2.6 on 2025-09-04 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do casal (apelido)')),
            ],
            options={
                'verbose_name': 'Casal',
                'verbose_name_plural': 'Casais',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('escopo_sugerido', models.CharField(choices=[('COMP', 'Compartilhada'), ('PESS', 'Pessoal')], default='COMP', help_text='Sugestão de escopo padrão (pode ser sobrescrita na despesa).', max_length=4)),
                ('icone', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DespesaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('escopo', models.CharField(choices=[('COMP', 'Compartilhada'), ('PESS', 'Pessoal')], default='COMP', max_length=4)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=1)),
                ('recorrente', models.BooleanField(default=True)),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual'), ('UNICA', 'Única')], default='MENSAL', max_length=10)),
                ('regra_rateio', models.CharField(choices=[('IGUAL', 'Igual para todos'), ('PERCENTUAL', 'Por percentual'), ('VALOR_FIXO', 'Por valor fixo')], default='IGUAL', help_text='Como dividir valores quando gerar lançamentos.', max_length=12)),
                ('ativo', models.BooleanField(default=True)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_modelo', to='despesas.casal')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_modelo', to='despesas.categoria')),
                ('dono_pessoal', models.ForeignKey(blank=True, help_text='Obrigatório se escopo = Pessoal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_pessoais_modelo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa (modelo)',
                'verbose_name_plural': 'Despesas (modelo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escopo', models.CharField(choices=[('COMP', 'Compartilhada'), ('PESS', 'Pessoal')], max_length=4)),
                ('descricao', models.CharField(blank=True, default='', max_length=180)),
                ('competencia', models.DateField(help_text='Use o 1º dia do mês como referência (YYYY-MM-01).')),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='despesas.casal')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='despesas.categoria')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('despesa_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='despesas.despesamodelo')),
                ('dono_pessoal', models.ForeignKey(blank=True, help_text='Obrigatório se escopo = Pessoal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_pessoais', to=settings.AUTH_USER_MODEL)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-competencia', 'data_vencimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MembroCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('apelido', models.CharField(blank=True, default='', max_length=50, verbose_name='Apelido no casal')),
                ('ativo', models.BooleanField(default=True)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='despesas.casal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_casal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro do casal',
                'verbose_name_plural': 'Membros do casal',
                'unique_together': {('casal', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='RateioLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='despesas.lancamento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rateio (lançamento)',
                'verbose_name_plural': 'Rateios (lançamento)',
                'unique_together': {('lancamento', 'membro')},
            },
        ),
        migrations.CreateModel(
            name='RegraRateioPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('despesa_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_padrao', to='despesas.despesamodelo')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_padrao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rateio padrão (modelo)',
                'verbose_name_plural': 'Rateios padrão (modelo)',
                'unique_together': {('despesa_modelo', 'membro')},
            },
        ),
    ]
