# Generated by Django 5.2.6 on 2025-09-08 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='parcela_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='parcelas_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTER', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'Amex'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10)),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dia_fechamento', models.PositiveSmallIntegerField(default=1)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='despesas.casal')),
            ],
            options={
                'verbose_name': 'Cartão de crédito',
                'verbose_name_plural': 'Cartões de crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=180)),
                ('escopo', models.CharField(choices=[('COMP', 'Compartilhada'), ('PESS', 'Pessoal')], default='COMP', max_length=4)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelas_total', models.PositiveSmallIntegerField(default=1)),
                ('primeira_competencia', models.DateField(help_text='Competência da 1ª parcela (YYYY-MM-01)')),
                ('primeiro_vencimento', models.DateField(help_text='Vencimento da 1ª parcela')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='despesas.cartaocredito')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_cartao', to='despesas.casal')),
                ('dono_pessoal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao_pessoais', to=settings.AUTH_USER_MODEL)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao_pagador', to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='despesas.subcategoria')),
            ],
            options={
                'verbose_name': 'Compra no cartão',
                'verbose_name_plural': 'Compras no cartão',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='compra_cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas', to='despesas.compracartao'),
        ),
    ]
