# Generated by Django 5.2.6 on 2025-09-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_lancamento_parcela_numero_lancamento_parcelas_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrocasal',
            name='salario_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do saláraio mensal para base de calculo.', max_digits=12),
        ),
    ]
