# Generated by Django 5.2.6 on 2025-09-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_membrocasal_salario_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='casal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='despesas.casal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('casal', 'nome')},
        ),
    ]
