# Generated by Django 5.2.6 on 2025-09-11 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_categoria_casal_alter_categoria_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('email_convidado', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=10)),
                ('casal_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='despesas.casal')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['-criado_em'],
            },
        ),
    ]
