# Generated by Django 5.2.6 on 2025-09-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_convite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convite',
        ),
    ]
