# Generated by Django 5.2.6 on 2025-10-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0007_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casal',
            options={'verbose_name': 'Grupo doméstico', 'verbose_name_plural': 'Grupos domésticos'},
        ),
        migrations.AlterModelOptions(
            name='membrocasal',
            options={'verbose_name': 'Membro do grupo', 'verbose_name_plural': 'Membros do grupo'},
        ),
        migrations.AlterField(
            model_name='casal',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do grupo (apelido)'),
        ),
        migrations.AlterField(
            model_name='membrocasal',
            name='apelido',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Apelido no grupo'),
        ),
        migrations.AlterField(
            model_name='membrocasal',
            name='salario_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base para relatórios.', max_digits=12),
        ),
    ]
